[platformio]
src_dir = .

[env:dueUSB]
platform = atmelsam
board = dueUSB
framework = arduino
monitor_speed = 115200

build_src_filter =
    +<src/main.cpp>
    +<lib/app/*.cpp>
    +<lib/core/link/*.cpp>
    +<lib/core/service/*.cpp>
    +<lib/core/transport/*.cpp>
    +<lib/core/runtime/*.cpp>
    +<lib/protocol/tlv/*.cpp>
    +<lib/services/led/*.cpp>
    +<lib/services/can/*.cpp>
    +<lib/drivers/can/*.cpp>
    +<lib/hal/board/*.cpp>
    +<lib/hal/transceivers/*.cpp>
    +<lib/diag/trace/*.cpp>

build_flags =
    -I include
    -I lib
    -I $PROJECT_PACKAGES_DIR/framework-arduino-sam/system/libsam/include
