[platformio]
src_dir = .

[env:dueUSB]
platform = atmelsam
board = dueUSB
framework = arduino
monitor_speed = 115200

build_src_filter =
    +<src/main.cpp>
    +<lib/core/link/*.cpp>
    +<lib/core/services/*.cpp>
    +<lib/core/transport/*.cpp>
    +<lib/services/can/driver/*.cpp>
    +<lib/services/can/service/*.cpp>
    +<lib/services/can/table/*.cpp>
    +<lib/services/can/protocol/*.cpp>
    +<lib/services/led/*.cpp>

build_flags =
    -I include
    -I lib
    -I $PROJECT_PACKAGES_DIR/framework-arduino-sam/system/libsam/include
